window.LERCH_GLOSSARY_REVIEW_BATCH_01 = {
  "generated": "2026-05-19",
  "source_tsv": "reports/lerch-glossary-review-batch-01.tsv",
  "source_word_index": "reports/lerch-word-index.tsv",
  "counts": {
    "likely_add_or_merge": 31,
    "merge_or_function_entry": 8,
    "review_lower_priority": 32,
    "review_high_value": 19
  },
  "rows": [
    {
      "lemma_key": "eskeri",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "eskeri",
      "suggested_gloss_en": "army, soldiers",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 68,
      "text_count": 4,
      "text_counts": "kauge-nyerib-u-hyeni:38; kauge-nyerib-u-sivani:21; degirmenci-ve-tilki:5; ali-agha-ladi-kelhani:4",
      "lemma_hints": "eskeri",
      "zazaki_variants": "eskêri; Eskêri; eskêrira; Êskêri",
      "lerch_variants": "e̱skéri; E̱skéri; e̱skéri; E̱skéri; e̱skérira; E̱sḱéri; Ē̱skéri; Eskéri",
      "context_gloss_hints": "army; soldiers; RECIP",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a01_l09:5",
      "example_token_zazaki": "eskêri",
      "example_token_lerch": "e̱skéri",
      "example_line_zazaki": "şawê venga êskêrê xoê di, eskêri dawang wa pyêru bêru pyêser,",
      "example_line_lerch": "šaú’e vé̱ṅga eskére χóe di, e̱skéri daú’āṅ wa pyéru béru pyesé̱r,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "deniai",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "deniai",
      "suggested_gloss_en": "woman, wife",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 23,
      "text_count": 3,
      "text_counts": "uc-kardes-masali:14; goin-puhu-kusunun-hikayesi:8; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "deniai",
      "zazaki_variants": "cênyay; Cênyay; dênyay",
      "lerch_variants": "d̮éniai; D̮éniai; d̮éniai; D̮éniai; d̮éniāi; déniai",
      "context_gloss_hints": "woman; wife",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g01_l01:4",
      "example_token_zazaki": "cênyay",
      "example_token_lerch": "d̮éniai",
      "example_line_zazaki": "Zêmanê veryê yaw mırdaw cênyay xoê bi, yaw kêynaw yaw lac",
      "example_line_lerch": "Zemā́ne ve̱ríe yau mí̥rdau d̮éniai χóe bī, yau keínau yau lād̮",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "pasai",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "pasai",
      "suggested_gloss_en": "pasha, pasha title",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 20,
      "text_count": 1,
      "text_counts": "degirmenci-ve-tilki:20",
      "lemma_hints": "pasai",
      "zazaki_variants": "paşay; Paşay",
      "lerch_variants": "pašai; pašaí; Pašaí; Pašai",
      "context_gloss_hints": "pasha",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf02_l10:5",
      "example_token_zazaki": "paşay",
      "example_token_lerch": "pašai",
      "example_line_zazaki": "Luê weriştê, şyê Mısr, şi paşay Mısr 'hêt, temênê kêrd. Pa-",
      "example_line_lerch": "Lú’e we̱ríšte, šíe Mi̥sr, šī pašai Mí̥sr h̔et, té̱mene kerd. Pa-",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "tinu",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "tinu",
      "suggested_gloss_en": "there is not / does not exist",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 18,
      "text_count": 7,
      "text_counts": "kauge-nyerib-u-hyeni:10; goin-puhu-kusunun-hikayesi:2; uc-kardes-masali:2; ali-agha-ladi-kelhani:1; degirmenci-ve-tilki:1; gespraech-mit-hassan:1; kauge-nyerib-u-sivani:1",
      "lemma_hints": "tinu",
      "zazaki_variants": "çinyu; çinu; çınu",
      "lerch_variants": "t̮ínu,; t̮íńu.; t̮ínu.; t̮íńu.; t̮íńu,; t̮íńu,; t̮í̥nu; t̮í̥nu,",
      "context_gloss_hints": "there is none; there is not; is not; does not exist",
      "related_glossary_hits": "tihü [lerch_glossary_p206_r0222:entry]: ist nicht, 55.12-13. Vgl. Krm. tune,",
      "example_ref": "ali-agha-ladi-kelhani:a03_l02:8",
      "example_token_zazaki": "çinyu",
      "example_token_lerch": "t̮íńu,",
      "example_line_zazaki": "ma mebêrê, tê xaini, bawki mê serêdê aqıl çinyu, rocêy ramazanyu,",
      "example_line_lerch": "mā mé̱bere, te χa’íni, baúki me sé̱rede áqi̥l t̮íńu, rṓd̮ei ramazányu,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "kagit",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "kagit",
      "suggested_gloss_en": "paper, letter",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 17,
      "text_count": 1,
      "text_counts": "uc-kardes-masali:17",
      "lemma_hints": "kagit",
      "zazaki_variants": "kağit",
      "lerch_variants": "kaγít",
      "context_gloss_hints": "",
      "related_glossary_hits": "",
      "example_ref": "uc-kardes-masali:tb03_l01:5",
      "example_token_zazaki": "kağit",
      "example_token_lerch": "kaγít",
      "example_line_zazaki": "maci yêri. Dyaw werişt, yaw kağit noşt, da 'Hasanêkira, va kê:",
      "example_line_lerch": "mā́d̮i yẹ̄́rí. D́au we̱ríšt, yau kaγít no̤št, dā H̔asanékira, vā ke:",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "het",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "het",
      "suggested_gloss_en": "side, direction",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 14,
      "text_count": 5,
      "text_counts": "uc-kardes-masali:7; degirmenci-ve-tilki:3; ali-agha-ladi-kelhani:2; goin-puhu-kusunun-hikayesi:1; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "het",
      "zazaki_variants": "'hêt; 'het",
      "lerch_variants": "h̔ēt,; h̔et,; h̔et.; h̔e̱t,; h̔e̱t; h̔ēt.; h̔e̱t.",
      "context_gloss_hints": "side; to",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a02_l08:2",
      "example_token_zazaki": "'hêt",
      "example_token_lerch": "h̔ēt.",
      "example_line_zazaki": "Qasim ağa 'hêt. Qasim ağa werişt bê aspar, kawta eskêri vêr,",
      "example_line_lerch": "Qasím aγá h̔ēt. Qasím aγá we̱ríšt be aspā́r, kaúta e̱skéri ver,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "gelanke",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "gelanke",
      "suggested_gloss_en": "occasion, time/event",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 14,
      "text_count": 3,
      "text_counts": "uc-kardes-masali:9; kauge-nyerib-u-sivani:4; ali-agha-ladi-kelhani:1",
      "lemma_hints": "gelanke",
      "zazaki_variants": "gêlankê",
      "lerch_variants": "gelā́ṅke; gelā́ṅke; gelāṅke; gelānke",
      "context_gloss_hints": "occasion",
      "related_glossary_hits": "gelähke [lerch_glossary_p204_r0182:entry]: Mal. Ön’a gelähke, dieses Mal.",
      "example_ref": "ali-agha-ladi-kelhani:a03_l12:5",
      "example_token_zazaki": "gêlankê",
      "example_token_lerch": "gelā́ṅke",
      "example_line_zazaki": "şyêri, ez serêy twê ena gêlankê wêna. A'hmêdi veng da va kê:",
      "example_line_lerch": "šyẹ̄́ri, e̱z sé̱rei túe ḗ̱n’a gelā́ṅke wén’a. Ah̔médi ve̱ṅg dā vā ke:",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "gai",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "gai",
      "suggested_gloss_en": "ox",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 11,
      "text_count": 1,
      "text_counts": "uc-kardes-masali:11",
      "lemma_hints": "gai",
      "zazaki_variants": "gay",
      "lerch_variants": "gai; gaí",
      "context_gloss_hints": "ox",
      "related_glossary_hits": "ga [lerch_glossary_p204_r0176:entry]: ox, bullock",
      "example_ref": "uc-kardes-masali:tb03_l09:8",
      "example_token_zazaki": "gay",
      "example_token_lerch": "gai",
      "example_line_zazaki": "noşt, ekê enoê merdüm enoê kağit anu kêyê, gay bwêri pilaw",
      "example_line_lerch": "no̤št, é̱ke ḗ̱n’oe me̱rdṳ́m ḗ̱n’oe kaγít ā́nu keíye, gai búeri pilaú",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "pasa",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "pasa",
      "suggested_gloss_en": "pasha",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 11,
      "text_count": 1,
      "text_counts": "degirmenci-ve-tilki:11",
      "lemma_hints": "pasa",
      "zazaki_variants": "paşa; Paşa",
      "lerch_variants": "pašá; Pašá; pašá,",
      "context_gloss_hints": "pasha",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf03_l03:9",
      "example_token_zazaki": "paşa",
      "example_token_lerch": "pašá",
      "example_line_zazaki": "lingê, mê enoê dest tepişt awkêra vecyaya tebêr, çêmçêqu paşa",
      "example_line_lerch": "líṅge, me ḗ̱n’oe de̱st te̱píšt aúkera ve̱d̮iáya te̱bér, t̮emt̮equ pašá",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "namei",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "namei",
      "suggested_gloss_en": "name",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 9,
      "text_count": 4,
      "text_counts": "uc-kardes-masali:5; gespraech-mit-hassan:2; ali-agha-ladi-kelhani:1; degirmenci-ve-tilki:1",
      "lemma_hints": "namei",
      "zazaki_variants": "namêy; Namêy",
      "lerch_variants": "nameí; Nāmeí; Nameí; nāmeí",
      "context_gloss_hints": "name",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a01_l01:7",
      "example_token_zazaki": "Namêy",
      "example_token_lerch": "Nameí",
      "example_line_zazaki": "Ali ağa laci Kêlhani mirêy na'hêy Karbegani. Namêy daway",
      "example_line_lerch": "Áli aγá lā́d̮i Kelháni mírei nah̔eí Karbe̱gā́ni. Nameí daú’ai",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "emsoe",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "emsoe",
      "suggested_gloss_en": "tonight",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 9,
      "text_count": 3,
      "text_counts": "uc-kardes-masali:5; kauge-nyerib-u-hyeni:3; kauge-nyerib-u-sivani:1",
      "lemma_hints": "emsoe",
      "zazaki_variants": "emşoê",
      "lerch_variants": "é̱mšoe; ḗ̱mšoe; é̱mšoe",
      "context_gloss_hints": "tonight",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h04_l03:5",
      "example_token_zazaki": "emşoê",
      "example_token_lerch": "é̱mšoe",
      "example_line_zazaki": "Daqma begiri 'Hyênê va kê: emşoê muqaytê xoê bê, ez",
      "example_line_lerch": "Dáqma bé̱giri Hʿyẹ̄́ne vā ke: é̱mšoe muqaíte χóe be, e̱z",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "hete",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "hete",
      "suggested_gloss_en": "side, direction, with/to",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 9,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:7; ali-agha-ladi-kelhani:2",
      "lemma_hints": "hete",
      "zazaki_variants": "'hêtê; hetê; 'hetê",
      "lerch_variants": "h̔ēte; hé̱te; h̔é̱te",
      "context_gloss_hints": "with; side",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a02_l10:5",
      "example_token_zazaki": "hetê",
      "example_token_lerch": "hé̱te",
      "example_line_zazaki": "Qasim ağa şi Ali ağay hetê ronişt va kê: ağa, ez ama twêra ric",
      "example_line_lerch": "Qasím aγá ši Áli aγaí hé̱te rōníšt vā ke: aγá, e̱z amá túera rīd̮",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "keinek",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "keinek",
      "suggested_gloss_en": "girl",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 9,
      "text_count": 1,
      "text_counts": "goin-puhu-kusunun-hikayesi:9",
      "lemma_hints": "keinek",
      "zazaki_variants": "Kêynêk; kêynêk; kêynêkra",
      "lerch_variants": "Keínek; keínek; keínekra",
      "context_gloss_hints": "girl; RECIP",
      "related_glossary_hits": "kcina [lerch_glossary_p203_r0145:entry]: Tochter, Mädchen. Ygl.altb: ka'\\n\\n, Jüngling, Jung- frau , kainü puella ( Itrr... | keincka [lerch_glossary_p203_r0146:entry]: keineke, Diminutiv von keina, 80.4, s.",
      "example_ref": "goin-puhu-kusunun-hikayesi:g02_l03:3",
      "example_token_zazaki": "kêynêk",
      "example_token_lerch": "keínek",
      "example_line_zazaki": "Kêynêkê şwêna golikangdê; kêynêk rocêki yerêy golikana yêna,",
      "example_line_lerch": "Keíneke šuén’a gōlikā́ṅde; keínek rṓd̮eki yé̱rei gōlikā́na yén’a,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "daw",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "daw",
      "suggested_gloss_en": "village",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 8,
      "text_count": 3,
      "text_counts": "ali-agha-ladi-kelhani:3; kauge-nyerib-u-sivani:3; gespraech-mit-hassan:2",
      "lemma_hints": "daw",
      "zazaki_variants": "dawani; dawang; dawê; dawana",
      "lerch_variants": "dauā́ni; daú’āṅ; daúe; dauwā́na",
      "context_gloss_hints": "village; PL; EZ/OBL; EZ/GEN; OBL/GOAL",
      "related_glossary_hits": "dau [lerch_glossary_p208_r0289:entry]: Dorf. Vgl. npers: 0a. | d'au [lerch_glossary_p209_r0325:entry]: Dev. Vgl. JC: daöva; altb: da6va (s. Brnf. Coinni. s. I. Y. 8, 78; Brckh. Gl. s...",
      "example_ref": "ali-agha-ladi-kelhani:a01_l02:6",
      "example_token_zazaki": "dawang",
      "example_token_lerch": "daú’āṅ",
      "example_line_zazaki": "Ali ağay Narbyêş. Ali ağa çêhêr dawang da pyêru, hiris û çêhêr",
      "example_line_lerch": "Áli aγaí Nārbyẹ̄́š. Áli aγá t̮ehér daú’āṅ dā pyérū, híris u t̮ehér",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "etia",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "etia",
      "suggested_gloss_en": "here",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 8,
      "text_count": 3,
      "text_counts": "uc-kardes-masali:4; goin-puhu-kusunun-hikayesi:2; kauge-nyerib-u-hyeni:2",
      "lemma_hints": "etia",
      "zazaki_variants": "etya; etyara",
      "lerch_variants": "e̱tía; e̱tía; e̱tía.; e̱tia; e̱tíara",
      "context_gloss_hints": "here; here (modern Zazaki: itiya); ABL",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g02_l13:5",
      "example_token_zazaki": "etya",
      "example_token_lerch": "e̱tía",
      "example_line_zazaki": "'hêni twêri golêkangdê nyêşwêna, ez etya nyêvêndêna.",
      "example_line_lerch": "h̔én’i túeri gōlekā́ṅde ńešuén’a, e̱z e̱tía ńevendén’a.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "hadre",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "hadre",
      "suggested_gloss_en": "ready",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 8,
      "text_count": 3,
      "text_counts": "kauge-nyerib-u-hyeni:4; kauge-nyerib-u-sivani:3; uc-kardes-masali:1",
      "lemma_hints": "hadre",
      "zazaki_variants": "'hadre; 'hadrê",
      "lerch_variants": "h̔adré̱; h̔ādré̱; h̔ādré; h̔adré̱; h̔adré̱",
      "context_gloss_hints": "ready",
      "related_glossary_hits": "hadrü [lerch_glossary_p200_r0082:entry]: hadre, bereit, fertig, hadraü, ist fertig, hadre kerdu, bereite, 52.7.",
      "example_ref": "kauge-nyerib-u-hyeni:h03_l01:0",
      "example_token_zazaki": "'hadre",
      "example_token_lerch": "h̔adré̱",
      "example_line_zazaki": "'hadre kêri, qam rocukê 'Hyênêra 'haberê amêyê ma kawğe kêni.",
      "example_line_lerch": "h̔adré̱ kéri, qām rṓd̮uke Hʿyẹ̄́nera h̔abé̱re āmeíye mā kauγé̱ kén’i.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "meiste",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "meiste",
      "suggested_gloss_en": "tomorrow",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 8,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-hyeni:6; kauge-nyerib-u-sivani:2",
      "lemma_hints": "meiste",
      "zazaki_variants": "mêyştê",
      "lerch_variants": "meíšte",
      "context_gloss_hints": "tomorrow",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h03_l08:9",
      "example_token_zazaki": "mêyştê",
      "example_token_lerch": "meíšte",
      "example_line_zazaki": "erşawutê 'Hyênê Daqma begiri va kê: roci pangcinê, nyê mêyştê byê,",
      "example_line_lerch": "e̱ršau’úte Hʿyẹ̄́ne Dáqma bé̱giri vā ke: rōd̮i paṅd̮íne, ńe meíšte bye,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "rod",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "rod",
      "suggested_gloss_en": "day",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 7,
      "text_count": 3,
      "text_counts": "kauge-nyerib-u-hyeni:5; degirmenci-ve-tilki:1; kauge-nyerib-u-sivani:1",
      "lemma_hints": "rod",
      "zazaki_variants": "roc; Roc",
      "lerch_variants": "rōd̮; Rōd̮; rōd̮,",
      "context_gloss_hints": "day(s); day; days",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf01_l02:1",
      "example_token_zazaki": "Roc",
      "example_token_lerch": "Rōd̮",
      "example_line_zazaki": "nayni. Roc yêkê beri ari qafêlna şê kêyê, şawê kêyê ra kawt,",
      "example_line_lerch": "naíni. Rōd̮ yéke bé̱ri ārí qáfelnā šẹ̄ keíye, šaú’e keíye rā kaut,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "soba",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "soba",
      "suggested_gloss_en": "morning",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 7,
      "text_count": 3,
      "text_counts": "uc-kardes-masali:5; ali-agha-ladi-kelhani:1; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "soba",
      "zazaki_variants": "soba; Soba",
      "lerch_variants": "so̤bā́; So̤bá; söbā́; sobā́.; So̤bā́",
      "context_gloss_hints": "morning",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a04_l08:6",
      "example_token_zazaki": "Soba",
      "example_token_lerch": "So̤bá",
      "example_line_zazaki": "hêyşt merdümi ğaribana pyêru mêndi wadedê. Soba Mêlay Rêsa",
      "example_line_lerch": "heišt me̱rdṳ́mi γaribā́na pyéru méndi wáde̱de. So̤bá Mél’ai Resá",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "waxte",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "waxte",
      "suggested_gloss_en": "time",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 7,
      "text_count": 3,
      "text_counts": "kauge-nyerib-u-hyeni:3; gespraech-mit-hassan:2; kauge-nyerib-u-sivani:2",
      "lemma_hints": "waxte",
      "zazaki_variants": "waxtê",
      "lerch_variants": "wáχte; waχte; wā́χte",
      "context_gloss_hints": "time",
      "related_glossary_hits": "",
      "example_ref": "gespraech-mit-hassan:h03_l02:2",
      "example_token_zazaki": "waxtê",
      "example_token_lerch": "wáχte",
      "example_line_zazaki": "Şüma qam waxtê şwêni zozang?",
      "example_line_lerch": "Šṳ́ma qām wáχte šuén’i zozā́ṅ?",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "vist",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "vist",
      "suggested_gloss_en": "twenty",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 7,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-hyeni:5; kauge-nyerib-u-sivani:2",
      "lemma_hints": "vist",
      "zazaki_variants": "vist; Vist",
      "lerch_variants": "vīst; vīst; Vīst",
      "context_gloss_hints": "twenty",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h06_l09:10",
      "example_token_zazaki": "vist",
      "example_token_lerch": "vīst",
      "example_line_zazaki": "mawlêt bıdê mê. Xalef ağa va kê: 'haici, wa twêri vist roc mawlêt,",
      "example_line_lerch": "maulét bi̥dé me. Χalé̱f aγá vā ke: h̔á’id̮i, wa túeri vīst rōd̮ maulét,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "bani",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "bani",
      "suggested_gloss_en": "house(s)",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 6,
      "text_count": 2,
      "text_counts": "gespraech-mit-hassan:5; kauge-nyerib-u-sivani:1",
      "lemma_hints": "bani",
      "zazaki_variants": "bani; banidê",
      "lerch_variants": "bā́ni; bā́nide",
      "context_gloss_hints": "houses; LOC; house",
      "related_glossary_hits": "",
      "example_ref": "gespraech-mit-hassan:h02_l06:1",
      "example_token_zazaki": "bani",
      "example_token_lerch": "bā́ni",
      "example_line_zazaki": "Çendê bani dawe Kasan esti?",
      "example_line_lerch": "T̮é̱nde bā́ni daúe̱ Kasán é̱sti?",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "launa",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "launa",
      "suggested_gloss_en": "kissed",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 6,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-sivani:4; kauge-nyerib-u-hyeni:2",
      "lemma_hints": "launa",
      "zazaki_variants": "lawna",
      "lerch_variants": "launā́; launā",
      "context_gloss_hints": "kissed",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h09_l08:3",
      "example_token_zazaki": "lawna",
      "example_token_lerch": "launā",
      "example_line_zazaki": "Daqma beg şê, lawna Xalef ağay lingêru, Xalef ağay lawna Daqma",
      "example_line_lerch": "Dáqma be̱g šẹ̄, launā Χalé̱f aγái língeru, Χalé̱f aγái launā Dáqma",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "kidi",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "kidi",
      "suggested_gloss_en": "small",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 6,
      "text_count": 1,
      "text_counts": "uc-kardes-masali:6",
      "lemma_hints": "kidi",
      "zazaki_variants": "kıci",
      "lerch_variants": "ki̥d̮i; kí̥d̮i",
      "context_gloss_hints": "small",
      "related_glossary_hits": "kcina [lerch_glossary_p203_r0145:entry]: Tochter, Mädchen. Ygl.altb: ka'\\n\\n, Jüngling, Jung- frau , kainü puella ( Itrr...",
      "example_ref": "uc-kardes-masali:tb01_l01:9",
      "example_token_zazaki": "kıci",
      "example_token_lerch": "ki̥d̮i",
      "example_line_zazaki": "Cayki bi çi nyêbi, hiryê bêrai bi, namêy bêray kıci 'Hasanêk,",
      "example_line_lerch": "D̮aíkí bī t̮í ńébī, hī́rye berá’i bī, nameí beraí ki̥d̮i Hʿasanék,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "izmi",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "izmi",
      "suggested_gloss_en": "permission",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 5,
      "text_count": 3,
      "text_counts": "degirmenci-ve-tilki:2; kauge-nyerib-u-hyeni:2; uc-kardes-masali:1",
      "lemma_hints": "izmi",
      "zazaki_variants": "izmi",
      "lerch_variants": "ī́zmi; ī́zmí",
      "context_gloss_hints": "permission",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf02_l12:1",
      "example_token_zazaki": "izmi",
      "example_token_lerch": "ī́zmi",
      "example_line_zazaki": "êfêndim: izmi mê bıdê, ez twêri vaca. Paşay Mısri izmi luê da.",
      "example_line_lerch": "eféndim: ī́zmi me bi̥dé, e̱z túeri vā́d̮a. Pašaí Mi̥sri ī́zmi lú’e dā.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "vadi",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "vadi",
      "suggested_gloss_en": "say, tell",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 5,
      "text_count": 3,
      "text_counts": "uc-kardes-masali:3; gespraech-mit-hassan:1; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "vadi",
      "zazaki_variants": "vaci; vadi",
      "lerch_variants": "vā́d̮i; vā́d̮i; vā́di:",
      "context_gloss_hints": "say; tell",
      "related_glossary_hits": "va [lerch_glossary_p217_r0546:entry]: to say; to tell; to speak | va$ [lerch_glossary_p218_r0549:entry]: grass, weed",
      "example_ref": "gespraech-mit-hassan:h03_l15:2",
      "example_token_zazaki": "vaci",
      "example_token_lerch": "vā́d̮i",
      "example_line_zazaki": "Tı nyêşêni vaci kawğei Sivani û Avdula begi.",
      "example_line_lerch": "Ti̥ ńešén’i vā́d̮i kauγé̱’i Sivā́ni u Avdúla bé̱gi.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "esker",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "esker",
      "suggested_gloss_en": "army, soldier",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 5,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-hyeni:3; ali-agha-ladi-kelhani:2",
      "lemma_hints": "esker",
      "zazaki_variants": "eskêr; Eskêr",
      "lerch_variants": "e̱skér; e̱skér; E̱skér",
      "context_gloss_hints": "army; soldier",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a02_l07:8",
      "example_token_zazaki": "eskêr",
      "example_token_lerch": "e̱skér",
      "example_line_zazaki": "Dewi pyêru amêy pyêsêr, şawê werişti, çêhêr sêy eskêr vıcyay, amêy",
      "example_line_lerch": "Dé̱wi pyéru āmeí pyesér, šaú’e we̱ríšti, t̮ehér sei e̱skér vi̥d̮iai, āmeí",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "rez",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "rez",
      "suggested_gloss_en": "vineyard, vine",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 5,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-hyeni:4; gespraech-mit-hassan:1",
      "lemma_hints": "rez",
      "zazaki_variants": "rezan; rez",
      "lerch_variants": "re̱z; ré̱zān.; ré̱zān.; re̱zā́n",
      "context_gloss_hints": "vineyard; PL; vine",
      "related_glossary_hits": "",
      "example_ref": "gespraech-mit-hassan:h02_l12:1",
      "example_token_zazaki": "rez",
      "example_token_lerch": "re̱z",
      "example_line_zazaki": "nariyêr, rez êsti.",
      "example_line_lerch": "nāriyér, re̱z ésti.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "simsyeri",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "simsyeri",
      "suggested_gloss_en": "sword",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 5,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:4; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "simsyeri",
      "zazaki_variants": "şimşyêri; şımşyêri",
      "lerch_variants": "šimšyẹ̄́ri; ši̥mšyẹ̄́ri",
      "context_gloss_hints": "sword",
      "related_glossary_hits": "SimSyßr [lerch_glossary_p210_r0367:entry]: Schwert. Vgl. Krm. sür, syür.",
      "example_ref": "kauge-nyerib-u-hyeni:h02_l01:7",
      "example_token_zazaki": "şımşyêri",
      "example_token_lerch": "ši̥mšyẹ̄́ri",
      "example_line_zazaki": "xoê gêrawti tırsi xoê kêrd, xo dest şımşyêri xoê werand, şê merdümi",
      "example_line_lerch": "χóe geraúti ti̥rsi χóe kerd, χo de̱st ši̥mšyẹ̄́ri χóe we̱rā́nd, šẹ̄ me̱rdṳ́mi",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "deni",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "deni",
      "suggested_gloss_en": "woman",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "goin-puhu-kusunun-hikayesi:5",
      "lemma_hints": "deni",
      "zazaki_variants": "cêni; cênira; Cêni",
      "lerch_variants": "d̮éni; d̮énira; D̮éni; d̮énira,",
      "context_gloss_hints": "woman; RECIP",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g01_l02:8",
      "example_token_zazaki": "cêni",
      "example_token_lerch": "d̮éni",
      "example_line_zazaki": "têra bi. Cênyay merd, pêynıdê myêrdê şê yawna cêni ardê. Dı",
      "example_line_lerch": "terá bī. D̮éniai me̱rd, peíni̥de myérde šẹ̄ yaúna d̮éni ā́rde. Di̥",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "laser",
      "suggested_action": "likely_add_or_merge",
      "suggested_headword": "laser",
      "suggested_gloss_en": "flood",
      "suggested_gloss_tr": "",
      "rationale": "Frequent text-attested form with a stable context gloss and no current exact glossary match.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "degirmenci-ve-tilki:5",
      "lemma_hints": "laser",
      "zazaki_variants": "la; seri; laser",
      "lerch_variants": "la; sé̱ri; lasé̱r",
      "context_gloss_hints": "flood; flood-cont.",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf02_l14:5",
      "example_token_zazaki": "laser",
      "example_token_lerch": "lasé̱r",
      "example_line_zazaki": "zênu xoêri, yaw tuêrgê varay, laser ame pangc sêy êspari çêmçequ",
      "example_line_lerch": "zén’u χóeri, [yau tu’érge varai, lasé̱r āmé̱ paṅd̮ sei espā́ri t̮emt̮e̱qú",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "bi",
      "suggested_action": "merge_or_function_entry",
      "suggested_headword": "bi",
      "suggested_gloss_en": "CONJ/FUT; give; bring",
      "suggested_gloss_tr": "",
      "rationale": "conjunctive/future prefix and several short inflected verb forms; review as grammar/morpheme, not as a simple new lexical headword.",
      "token_count": 72,
      "text_count": 6,
      "text_counts": "kauge-nyerib-u-hyeni:22; uc-kardes-masali:15; ali-agha-ladi-kelhani:13; kauge-nyerib-u-sivani:11; degirmenci-ve-tilki:7; goin-puhu-kusunun-hikayesi:4",
      "lemma_hints": "bi-; bi",
      "zazaki_variants": "bi; bıdê; bıki; bıkşi; bıkêri; byari; bıgê; bıgi",
      "lerch_variants": "bi̥dé,; bi; bi̥kí,; bi̥dé; bi̥kší.; bíeri; bī; bi̥ké.",
      "context_gloss_hints": "CONJ/FUT; give; bring; was; kill; to; fight/do; do/fight",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a01_l08:2",
      "example_token_zazaki": "byari",
      "example_token_lerch": "biā́ri",
      "example_line_zazaki": "Ali ağay byari daw. Qasim ağa va kê: ma Ali ağay bê'hapêyni, ma",
      "example_line_lerch": "Áli aγaí biā́ri dau. Qasím aγá vā ke: mā Áli aγaí beh̔apeíni, mā",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "ne",
      "suggested_action": "merge_or_function_entry",
      "suggested_headword": "ne",
      "suggested_gloss_en": "NEG; spare/leave; not",
      "suggested_gloss_tr": "",
      "rationale": "negative particle/prefix; connect to a negative morpheme entry rather than adding every inflected form.",
      "token_count": 40,
      "text_count": 7,
      "text_counts": "kauge-nyerib-u-hyeni:17; ali-agha-ladi-kelhani:7; kauge-nyerib-u-sivani:7; uc-kardes-masali:4; degirmenci-ve-tilki:2; goin-puhu-kusunun-hikayesi:2; gespraech-mit-hassan:1",
      "lemma_hints": "ne-; ne",
      "zazaki_variants": "nyê; nyêvêrdana; nê; nyêşyêna; nyêdana; nyêkêna; nyêmiri; nyêbê",
      "lerch_variants": "ńešyén’a; ńeverdā́na,; ńe; ńe; ńémiri; ne-; ńébe,; ńegeraút.",
      "context_gloss_hints": "NEG; spare/leave; not; be; give; now; die; be able",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a01_l03:5",
      "example_token_zazaki": "nyêbê",
      "example_token_lerch": "ńébe,",
      "example_line_zazaki": "kişti. Çawdi Ali ağay çi nyêbê, çewi desti Ali ağay nyêgêrawt. Ali",
      "example_line_lerch": "kíšti. T̮aúdi Áli aγaí t̮i ńébe, t̮é̱wi dé̱sti Áli aγaí ńegeraút. Áli",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "de",
      "suggested_action": "merge_or_function_entry",
      "suggested_headword": "de",
      "suggested_gloss_en": "in; to him",
      "suggested_gloss_tr": "",
      "rationale": "locative/dative element and short pronoun-like forms; review under grammar/function entries.",
      "token_count": 12,
      "text_count": 4,
      "text_counts": "uc-kardes-masali:7; degirmenci-ve-tilki:2; goin-puhu-kusunun-hikayesi:2; ali-agha-ladi-kelhani:1",
      "lemma_hints": "de",
      "zazaki_variants": "dê; cê; dye",
      "lerch_variants": "de,; de; d̮e.; de.; d̮é-; dé; d́é̱-; dé,",
      "context_gloss_hints": "in; to him",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a03_l06:5",
      "example_token_zazaki": "cê",
      "example_token_lerch": "d̮e.",
      "example_line_zazaki": "kişêni. 'Hali xancêray A'hmêdi nyêday cê. 'Hal şê tebêr, eskêri",
      "example_line_lerch": "kišén’i. Hʿāli χand̮érai Ah̔médi ńédai d̮e. Hʿāl šẹ̄ te̱bér, e̱skéri",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "na",
      "suggested_action": "merge_or_function_entry",
      "suggested_headword": "na",
      "suggested_gloss_en": "ended; not",
      "suggested_gloss_tr": "",
      "rationale": "short negative/demonstrative/verb-form ambiguity; review under existing function words if possible.",
      "token_count": 12,
      "text_count": 4,
      "text_counts": "uc-kardes-masali:6; kauge-nyerib-u-hyeni:4; goin-puhu-kusunun-hikayesi:1; kauge-nyerib-u-sivani:1",
      "lemma_hints": "na",
      "zazaki_variants": "na; nya",
      "lerch_variants": "nā; ńa; nā.; ńa,; nā.; na,",
      "context_gloss_hints": "ended; not",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g03_l02:1",
      "example_token_zazaki": "nya",
      "example_token_lerch": "ńa,",
      "example_line_zazaki": "sağê nya, 'hêyrkê mê bêray twê nyêdi, nyê ez vêndêna, nyê tı vındê.",
      "example_line_lerch": "sáγe ńa, h̔eirke me beraí túe ńédī, ńe e̱z vendén’a, ńe ti̥ ví̥nde.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "we",
      "suggested_action": "merge_or_function_entry",
      "suggested_headword": "we",
      "suggested_gloss_en": "out-; let; and",
      "suggested_gloss_tr": "",
      "rationale": "prefix/particle in compounds and verbs; review as morpheme/function element.",
      "token_count": 5,
      "text_count": 5,
      "text_counts": "ali-agha-ladi-kelhani:1; degirmenci-ve-tilki:1; kauge-nyerib-u-hyeni:1; kauge-nyerib-u-sivani:1; uc-kardes-masali:1",
      "lemma_hints": "we",
      "zazaki_variants": "we; wê",
      "lerch_variants": "we̱; we̱-; we-",
      "context_gloss_hints": "out-; let; and; to; up",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a04_l10:10",
      "example_token_zazaki": "we",
      "example_token_lerch": "we̱-",
      "example_line_zazaki": "aylana dês û hêyşt teni merdümi ğaribana 'hetya byêri beri we-",
      "example_line_lerch": "aílāna des u heíšt té̱ni me̱rdṳ́mi γaribā́na h̔é̱tia bíeri bé̱ri we̱-",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "ge",
      "suggested_action": "merge_or_function_entry",
      "suggested_headword": "ge",
      "suggested_gloss_en": "put on; go; occasion-",
      "suggested_gloss_tr": "",
      "rationale": "short preverb/verb fragment in multiple contexts; review as grammar/morpheme.",
      "token_count": 5,
      "text_count": 4,
      "text_counts": "kauge-nyerib-u-sivani:2; degirmenci-ve-tilki:1; goin-puhu-kusunun-hikayesi:1; uc-kardes-masali:1",
      "lemma_hints": "ge",
      "zazaki_variants": "gê",
      "lerch_variants": "ge-; ǵe,",
      "context_gloss_hints": "put on; go; occasion-; took-; took",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf03_l13:4",
      "example_token_zazaki": "gê",
      "example_token_lerch": "ǵe,",
      "example_line_zazaki": "enoê qati kincang pêra gê, ma şyêri paşadê Mısri 'hêt.",
      "example_line_lerch": "ḗ̱n’oe qáti kind̮áṅ perá ǵe, mā šyẹ̄́ri pašáde Mí̥sri h̔et.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "ka",
      "suggested_action": "merge_or_function_entry",
      "suggested_headword": "ka",
      "suggested_gloss_en": "would",
      "suggested_gloss_tr": "",
      "rationale": "conditional/subordinator/auxiliary-like short form; review as function item.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-sivani:2; uc-kardes-masali:2",
      "lemma_hints": "ka",
      "zazaki_variants": "ka",
      "lerch_variants": "ka-; ka; ka,",
      "context_gloss_hints": "would",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-sivani:s05_l14:2",
      "example_token_zazaki": "ka",
      "example_token_lerch": "ka",
      "example_line_zazaki": "nyêdani, ez ka pêynyay dawani Nyêribi veşna, heminê taalan ka, çım-",
      "example_line_lerch": "ńedā́ni, e̱z ka peińai dauā́ni Ńeríbi vé̱šna, hé̱mine tá’alan ka, t̮i̥m-",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "la",
      "suggested_action": "merge_or_function_entry",
      "suggested_headword": "la",
      "suggested_gloss_en": "but-",
      "suggested_gloss_tr": "",
      "rationale": "short connector/phrase element; review before adding as lexical headword.",
      "token_count": 3,
      "text_count": 3,
      "text_counts": "goin-puhu-kusunun-hikayesi:1; kauge-nyerib-u-sivani:1; uc-kardes-masali:1",
      "lemma_hints": "la",
      "zazaki_variants": "la",
      "lerch_variants": "la; la-",
      "context_gloss_hints": "but-",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g04_l01:5",
      "example_token_zazaki": "la",
      "example_token_lerch": "la",
      "example_line_zazaki": "va kê cênira, kêynay kopeki, la qami kiştu ênoê lacêk? Zwani",
      "example_line_lerch": "vā ke d̮énira, keínai kōpé̱ki, la qā́mi kíštu ẹ̄́n’oe lā́d̮ek? Zuā́ni",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "begi",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "begi",
      "suggested_gloss_en": "Beg, title; Beg; GOAL/RECIP",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 37,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-hyeni:34; gespraech-mit-hassan:3",
      "lemma_hints": "begi",
      "zazaki_variants": "begi; begiri; begira",
      "lerch_variants": "bé̱gi; bé̱giri; bé̱gi,; bé̱gi; bé̱gi.; bé̱gí; bé̱gira; bé̱gira.",
      "context_gloss_hints": "Beg, title; Beg; GOAL/RECIP; ABL/SOURCE",
      "related_glossary_hits": "",
      "example_ref": "gespraech-mit-hassan:h03_l10:9",
      "example_token_zazaki": "begi",
      "example_token_lerch": "bé̱gi",
      "example_line_zazaki": "di, ez şya kawğei Nyêribi û 'Hyêni, kawğei E'hmêd begi û Sivani",
      "example_line_lerch": "dī, e̱z šía kauγé̱’i Ńeríbi u Hʿyẹ̄́ni, kauγé̱’i E̱h̔méd bé̱gi u Sivā́ni",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "lad",
      "suggested_action": "review_high_value",
      "suggested_headword": "lad",
      "suggested_gloss_en": "son; EZ/GEN; PL",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 21,
      "text_count": 4,
      "text_counts": "ali-agha-ladi-kelhani:9; kauge-nyerib-u-sivani:6; goin-puhu-kusunun-hikayesi:3; uc-kardes-masali:3",
      "lemma_hints": "lad",
      "zazaki_variants": "laci; lacana; Laci; lacan; lac; lacêku",
      "lerch_variants": "Lā́d̮i; lā́d̮i; lad̮ā́na; lā́d̮i; lád̮ān; lād̮ā́na,; lā́d̮āna; lād̮",
      "context_gloss_hints": "son; EZ/GEN; PL; EZ/OBL; boy; son/boy; DIM/one; OBL",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a01_l01:2",
      "example_token_zazaki": "laci",
      "example_token_lerch": "lā́d̮i",
      "example_line_zazaki": "Ali ağa laci Kêlhani mirêy na'hêy Karbegani. Namêy daway",
      "example_line_lerch": "Áli aγá lā́d̮i Kelháni mírei nah̔eí Karbe̱gā́ni. Nameí daú’ai",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "tera",
      "suggested_action": "review_high_value",
      "suggested_headword": "tera",
      "suggested_gloss_en": "from; with; off",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 10,
      "text_count": 5,
      "text_counts": "kauge-nyerib-u-hyeni:4; goin-puhu-kusunun-hikayesi:3; degirmenci-ve-tilki:1; kauge-nyerib-u-sivani:1; uc-kardes-masali:1",
      "lemma_hints": "tera",
      "zazaki_variants": "têra",
      "lerch_variants": "terá; terá; téra; téra",
      "context_gloss_hints": "from; with; off",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf04_l13:7",
      "example_token_zazaki": "têra",
      "example_token_lerch": "terá",
      "example_line_zazaki": "lwêra: paşay Mısri nêkay yênu, serêy mê têra kênu. Lwê va kê:",
      "example_line_lerch": "lúera: pašaí Mí̥sri nekāí yén’u, sé̱rei me terá kén’u. Lúe vā ke:",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "sue",
      "suggested_action": "review_high_value",
      "suggested_headword": "sue",
      "suggested_gloss_en": "go; come",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 10,
      "text_count": 4,
      "text_counts": "uc-kardes-masali:4; degirmenci-ve-tilki:3; goin-puhu-kusunun-hikayesi:2; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "sue",
      "zazaki_variants": "şwê",
      "lerch_variants": "šúe,; šúe; šúe; šúe,",
      "context_gloss_hints": "go; come",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf03_l12:4",
      "example_token_zazaki": "şwê",
      "example_token_lerch": "šúe",
      "example_line_zazaki": "şadê Mısri wayştê, warzê, şwê 'hemam, xoê bışu, temiz kê, byê,",
      "example_line_lerch": "šáde Mi̥sri waíšte, wárze, šúe h̔é̱m’ām, χóe bi̥šú, te̱míz ke, bye,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "enie",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "enie",
      "suggested_gloss_en": "these",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 8,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:7; ali-agha-ladi-kelhani:1",
      "lemma_hints": "enie",
      "zazaki_variants": "enyê; Enyê; ênyê; Ênyê",
      "lerch_variants": "ḗ̱n’ie; ḗ̱n’ie; Ḗ̱n’ie; én’ie; Én’ie",
      "context_gloss_hints": "these",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a02_l04:1",
      "example_token_zazaki": "enyê",
      "example_token_lerch": "ḗ̱n’ie",
      "example_line_zazaki": "ağa enyê wirdi şi, kêy Ali ağay ard dawê, çêhêr hemê lacana",
      "example_line_lerch": "aγá ḗ̱n’ie wírdi šī, kei Áli aγaí ārd daú’e, t̮ehér hé̱me lad̮ā́na",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "kauta",
      "suggested_action": "review_high_value",
      "suggested_headword": "kauta",
      "suggested_gloss_en": "went",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 7,
      "text_count": 4,
      "text_counts": "ali-agha-ladi-kelhani:2; kauge-nyerib-u-hyeni:2; kauge-nyerib-u-sivani:2; uc-kardes-masali:1",
      "lemma_hints": "kauta",
      "zazaki_variants": "kawta",
      "lerch_variants": "kaúta; kaúta,; kaúta; kautá",
      "context_gloss_hints": "went",
      "related_glossary_hits": "kaut [lerch_glossary_p202_r0120:entry]: fiel, 64.io; s. ra kaüta. kaüta rayer, auf den Weg fal- lend, d. h. sich auf de...",
      "example_ref": "ali-agha-ladi-kelhani:a02_l08:8",
      "example_token_zazaki": "kawta",
      "example_token_lerch": "kaúta",
      "example_line_zazaki": "Qasim ağa 'hêt. Qasim ağa werişt bê aspar, kawta eskêri vêr,",
      "example_line_lerch": "Qasím aγá h̔ēt. Qasím aγá we̱ríšt be aspā́r, kaúta e̱skéri ver,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "wena",
      "suggested_action": "review_high_value",
      "suggested_headword": "wena",
      "suggested_gloss_en": "cut; PRS.1SG",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 7,
      "text_count": 4,
      "text_counts": "uc-kardes-masali:3; kauge-nyerib-u-hyeni:2; ali-agha-ladi-kelhani:1; kauge-nyerib-u-sivani:1",
      "lemma_hints": "wena",
      "zazaki_variants": "wêna",
      "lerch_variants": "wén’a.; wén’a.",
      "context_gloss_hints": "cut; PRS.1SG",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a03_l12:6",
      "example_token_zazaki": "wêna",
      "example_token_lerch": "wén’a.",
      "example_line_zazaki": "şyêri, ez serêy twê ena gêlankê wêna. A'hmêdi veng da va kê:",
      "example_line_lerch": "šyẹ̄́ri, e̱z sé̱rei túe ḗ̱n’a gelā́ṅke wén’a. Ah̔médi ve̱ṅg dā vā ke:",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "auna",
      "suggested_action": "review_high_value",
      "suggested_headword": "auna",
      "suggested_gloss_en": "saw",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 7,
      "text_count": 3,
      "text_counts": "uc-kardes-masali:5; ali-agha-ladi-kelhani:1; kauge-nyerib-u-sivani:1",
      "lemma_hints": "auna",
      "zazaki_variants": "awnya; awna",
      "lerch_variants": "auńā́; auńā́; auná; aunā́; auńá,",
      "context_gloss_hints": "saw",
      "related_glossary_hits": "aunaürike [lerch_glossary_p197_r0005:entry]: Schakal.",
      "example_ref": "ali-agha-ladi-kelhani:a03_l14:2",
      "example_token_zazaki": "awnya",
      "example_token_lerch": "auńā́",
      "example_line_zazaki": "bıkşu. A'hmêd awnya dyêsi wedi, yaw şıbakê 'ha dyêsê wedidê, desti",
      "example_line_lerch": "bi̥kšú. Ah̔méd auńā́ d́ési we̱dí, yau ši̥bā́ke h̔ā d́ése wé̱dide, dé̱sti",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "suena",
      "suggested_action": "review_high_value",
      "suggested_headword": "suena",
      "suggested_gloss_en": "I go; goes",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 7,
      "text_count": 3,
      "text_counts": "goin-puhu-kusunun-hikayesi:3; uc-kardes-masali:3; degirmenci-ve-tilki:1",
      "lemma_hints": "suena",
      "zazaki_variants": "şwêna",
      "lerch_variants": "šuén’a; šuén’a.; šuen’a; šuen’a,",
      "context_gloss_hints": "I go; goes",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf05_l04:5",
      "example_token_zazaki": "şwêna",
      "example_token_lerch": "šuen’a",
      "example_line_zazaki": "lwêra: mıri awkê byarê, ez şwêna dêsmaç. Lwê werişt şyê, awkê",
      "example_line_lerch": "lúera: mí̥ri aúke byā́re, e̱z šuen’a desmāt̮. Lúe we̱ríšt šíe, aúke",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "beg",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "beg",
      "suggested_gloss_en": "Beg, title; Beg",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 7,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-hyeni:6; gespraech-mit-hassan:1",
      "lemma_hints": "beg",
      "zazaki_variants": "beg; Beg",
      "lerch_variants": "be̱g; Be̱g",
      "context_gloss_hints": "Beg, title; Beg",
      "related_glossary_hits": "",
      "example_ref": "gespraech-mit-hassan:h02_l01:1",
      "example_token_zazaki": "Beg",
      "example_token_lerch": "Be̱g",
      "example_line_zazaki": "Ali Beg sıpyerdışu dawê Alduni estu.",
      "example_line_lerch": "Áli Be̱g si̥pye̱rdí̥šu daúe Aldū́ni é̱stu.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "wida",
      "suggested_action": "review_high_value",
      "suggested_headword": "wida",
      "suggested_gloss_en": "there; at once; immediately",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 6,
      "text_count": 4,
      "text_counts": "degirmenci-ve-tilki:2; kauge-nyerib-u-hyeni:2; kauge-nyerib-u-sivani:1; uc-kardes-masali:1",
      "lemma_hints": "wida",
      "zazaki_variants": "wica; Wica; wida",
      "lerch_variants": "wíd̮a; Wíd̮ā; wíd̮ā; widā; wid̮á; wid̮ā́",
      "context_gloss_hints": "there; at once; immediately",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf03_l04:3",
      "example_token_zazaki": "wica",
      "example_token_lerch": "wíd̮a",
      "example_line_zazaki": "erzê xoê mê wica ver daw, ez amêya Paşay Mısri va kê: êspar",
      "example_line_lerch": "é̱rz’e χóe me wíd̮a ve̱r daú, e̱z āmeía.] Pašaí Mí̥sri vā ke: espā́r",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "ameia",
      "suggested_action": "review_high_value",
      "suggested_headword": "ameia",
      "suggested_gloss_en": "I came; came",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 6,
      "text_count": 3,
      "text_counts": "kauge-nyerib-u-sivani:3; kauge-nyerib-u-hyeni:2; degirmenci-ve-tilki:1",
      "lemma_hints": "ameia",
      "zazaki_variants": "amêya",
      "lerch_variants": "āmeía; āmeía.]; āmeía:; āmeía.; ameía",
      "context_gloss_hints": "I came; came",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf03_l04:7",
      "example_token_zazaki": "amêya",
      "example_token_lerch": "āmeía.]",
      "example_line_zazaki": "erzê xoê mê wica ver daw, ez amêya Paşay Mısri va kê: êspar",
      "example_line_lerch": "é̱rz’e χóe me wíd̮a ve̱r daú, e̱z āmeía.] Pašaí Mí̥sri vā ke: espā́r",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "aunai",
      "suggested_action": "review_high_value",
      "suggested_headword": "aunai",
      "suggested_gloss_en": "saw",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 6,
      "text_count": 3,
      "text_counts": "kauge-nyerib-u-hyeni:3; uc-kardes-masali:2; degirmenci-ve-tilki:1",
      "lemma_hints": "aunai",
      "zazaki_variants": "awnyay; awnay",
      "lerch_variants": "auńaí; aunái",
      "context_gloss_hints": "saw",
      "related_glossary_hits": "aunaürike [lerch_glossary_p197_r0005:entry]: Schakal.",
      "example_ref": "degirmenci-ve-tilki:mf02_l01:2",
      "example_token_zazaki": "awnyay",
      "example_token_lerch": "auńaí",
      "example_line_zazaki": "newêtê pautê, awnyay kê myanê şawê yaw luê amêy zerê, şyê mê-",
      "example_line_lerch": "né̱wete pa’úte, auńaí ke myā́ne šaú’e yau lú’e āmeí zé̱re, šíe me-",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "desmat",
      "suggested_action": "review_high_value",
      "suggested_headword": "desmat",
      "suggested_gloss_en": "ablution",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 6,
      "text_count": 3,
      "text_counts": "degirmenci-ve-tilki:4; goin-puhu-kusunun-hikayesi:1; uc-kardes-masali:1",
      "lemma_hints": "desmat",
      "zazaki_variants": "dêsmaç",
      "lerch_variants": "desmā́t̮; desmāt̮,; desmāt̮.; desmā́t̮",
      "context_gloss_hints": "ablution",
      "related_glossary_hits": "desmäl [lerch_glossary_p208_r0305:entry]: Waschung. | D'esmüni [lerch_glossary_p209_r0338:entry]: Ortsname, 65.3. lyesmündi, Appellativ von D'es- müni. Vgl. Krm. naniik. newete...",
      "example_ref": "degirmenci-ve-tilki:mf05_l03:2",
      "example_token_zazaki": "dêsmaç",
      "example_token_lerch": "desmā́t̮",
      "example_line_zazaki": "nê, şwê, dêsmaç bigi, byê zerê, nêmac bıkê. Arêwangçi va kê",
      "example_line_lerch": "ne, šúe, desmā́t̮ bigí, bye zé̱re, nemā́d̮ bi̥ké. Ārewāṅt̮í vā ke",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "bu",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "bu",
      "suggested_gloss_en": "be",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 6,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:4; goin-puhu-kusunun-hikayesi:2",
      "lemma_hints": "bu",
      "zazaki_variants": "bu",
      "lerch_variants": "bu,; bu.; bū.; bú.",
      "context_gloss_hints": "be",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g02_l09:6",
      "example_token_zazaki": "bu",
      "example_token_lerch": "bu,",
      "example_line_zazaki": "Bawki kêynêkê xoêra va kê: 'hêyr bu, senyê bêray twê kişênu?",
      "example_line_lerch": "Baúki keíneke χóera vā ke: h̔eir bu, sḗ̱n’ie berāí túe kīšén’u?",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "tina",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "tina",
      "suggested_gloss_en": "cuts; is not there",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 6,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:5; goin-puhu-kusunun-hikayesi:1",
      "lemma_hints": "tina",
      "zazaki_variants": "çına; çina",
      "lerch_variants": "t̮í̥na; t̮ína,; t̮í̥na,; t̮í̥na,",
      "context_gloss_hints": "cuts; is not there",
      "related_glossary_hits": "tinau [lerch_glossary_p205_r0220:entry]: how is it? | tihü [lerch_glossary_p206_r0222:entry]: ist nicht, 55.12-13. Vgl. Krm. tune,",
      "example_ref": "goin-puhu-kusunun-hikayesi:g04_l05:9",
      "example_token_zazaki": "çına",
      "example_token_lerch": "t̮í̥na,",
      "example_line_zazaki": "amêy kêyê. Ek bêray xoê çınu, cênyay bawki xoê çına, şi, lawki",
      "example_line_lerch": "āmeí keíye. E̱k beraí χóe t̮í̥nu, d̮éniai baúki χóe t̮í̥na, šī, laúki",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "alah",
      "suggested_action": "review_high_value",
      "suggested_headword": "alah",
      "suggested_gloss_en": "God",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 5,
      "text_count": 4,
      "text_counts": "uc-kardes-masali:2; ali-agha-ladi-kelhani:1; degirmenci-ve-tilki:1; kauge-nyerib-u-sivani:1",
      "lemma_hints": "alah",
      "zazaki_variants": "Alah",
      "lerch_variants": "Aláh",
      "context_gloss_hints": "God",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a03_l13:0",
      "example_token_zazaki": "Alah",
      "example_token_lerch": "Aláh",
      "example_line_zazaki": "Alah izmê mê bıdu, ez twê veri êyxoê kışêna. 'Hal şi kê A'hmêdi",
      "example_line_lerch": "Aláh ī́zme me bi̥dú, e̱z túe vé̱ri eiχóe ki̥šén’a. Hʿāl ši ke Ah̔médi",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "bera",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "bera",
      "suggested_gloss_en": "brother; here",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:4; kauge-nyerib-u-sivani:1",
      "lemma_hints": "bera",
      "zazaki_variants": "bêra",
      "lerch_variants": "berá; berá; berā́; berá,",
      "context_gloss_hints": "brother; here",
      "related_glossary_hits": "ber äekit [lerch_glossary_p215_r0478:entry]: drang vor, 64 4. ber bidikni, dringet vor, 64.2.",
      "example_ref": "kauge-nyerib-u-sivani:s01_l10:1",
      "example_token_zazaki": "bêra",
      "example_token_lerch": "berá",
      "example_line_zazaki": "bıkêra, bêra twê ez dyang, lakimkê ez ha bêna, zor bêna. Laci",
      "example_line_lerch": "bi̥kéra, berá túe e̱z diā́ṅ, lakímke e̱z hā bén’a, zōr bén’a. Lā́d̮i",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "biaru",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "biaru",
      "suggested_gloss_en": "bring",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "uc-kardes-masali:5",
      "lemma_hints": "biaru",
      "zazaki_variants": "byaru",
      "lerch_variants": "biáru.",
      "context_gloss_hints": "bring",
      "related_glossary_hits": "",
      "example_ref": "uc-kardes-masali:tb03_l11:2",
      "example_token_zazaki": "byaru",
      "example_token_lerch": "biáru.",
      "example_line_zazaki": "ena pilaw byaru. 'Hasanêk da kağit dênyay dyewi. Cênyay dyewi ka-",
      "example_line_lerch": "ḗ̱n’a pilaú biáru. H̔asanék dā kaγít déniai d́é̱wi. D̮éniai d́é̱wi ka-",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "eistu",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "eistu",
      "suggested_gloss_en": "threw",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "goin-puhu-kusunun-hikayesi:5",
      "lemma_hints": "eistu",
      "zazaki_variants": "êyştu",
      "lerch_variants": "eíštu",
      "context_gloss_hints": "threw",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g02_l07:0",
      "example_token_zazaki": "êyştu",
      "example_token_lerch": "eíštu",
      "example_line_zazaki": "êyştu zêyndang. Sêbah wardêna, bawki xoêra vana: baw, mê em-",
      "example_line_lerch": "eíštu zeindā́ṅ. Sebáh wardén’a, bāúki χóera vā́na: bau, me é̱m-",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "kaugau",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "kaugau",
      "suggested_gloss_en": "fought",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "kauge-nyerib-u-hyeni:5",
      "lemma_hints": "kaugau",
      "zazaki_variants": "kawğaw",
      "lerch_variants": "kauγaú.; kauγaú,",
      "context_gloss_hints": "fought",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h03_l04:2",
      "example_token_zazaki": "kawğaw",
      "example_token_lerch": "kauγaú.",
      "example_line_zazaki": "kawğe ma kawğaw.",
      "example_line_lerch": "ḱauγé̱ mā kauγaú.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "keineke",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "keineke",
      "suggested_gloss_en": "the girl",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "goin-puhu-kusunun-hikayesi:5",
      "lemma_hints": "keineke",
      "zazaki_variants": "kêynêkê; Kêynêkê",
      "lerch_variants": "keíneke; Keíneke; keíneke,",
      "context_gloss_hints": "the girl",
      "related_glossary_hits": "keincka [lerch_glossary_p203_r0146:entry]: keineke, Diminutiv von keina, 80.4, s.",
      "example_ref": "goin-puhu-kusunun-hikayesi:g02_l03:0",
      "example_token_zazaki": "Kêynêkê",
      "example_token_lerch": "Keíneke",
      "example_line_zazaki": "Kêynêkê şwêna golikangdê; kêynêk rocêki yerêy golikana yêna,",
      "example_line_lerch": "Keíneke šuén’a gōlikā́ṅde; keínek rṓd̮eki yé̱rei gōlikā́na yén’a,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "ladeki",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "ladeki",
      "suggested_gloss_en": "of the boy",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "goin-puhu-kusunun-hikayesi:5",
      "lemma_hints": "ladeki",
      "zazaki_variants": "lacêki",
      "lerch_variants": "lā́d̮eki; lā́d̮eki",
      "context_gloss_hints": "of the boy",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g03_l05:3",
      "example_token_zazaki": "lacêki",
      "example_token_lerch": "lā́d̮eki",
      "example_line_zazaki": "zıbil wêlê kêrda lacêki ser. Bawki kêynêk amêy kêyê, cênyay",
      "example_line_lerch": "zi̥bíl wél’e kérda lā́d̮eki se̱r. Baúki keínek āmeí keíye, d̮éniai",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "nost",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "nost",
      "suggested_gloss_en": "wrote",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "uc-kardes-masali:5",
      "lemma_hints": "nost",
      "zazaki_variants": "noşt",
      "lerch_variants": "no̤št,; no̤št:; nošt,; nöšt,",
      "context_gloss_hints": "wrote",
      "related_glossary_hits": "",
      "example_ref": "uc-kardes-masali:tb03_l01:6",
      "example_token_zazaki": "noşt",
      "example_token_lerch": "no̤št,",
      "example_line_zazaki": "maci yêri. Dyaw werişt, yaw kağit noşt, da 'Hasanêkira, va kê:",
      "example_line_lerch": "mā́d̮i yẹ̄́rí. D́au we̱ríšt, yau kaγít no̤št, dā H̔asanékira, vā ke:",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "nostu",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "nostu",
      "suggested_gloss_en": "wrote",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "uc-kardes-masali:5",
      "lemma_hints": "nostu",
      "zazaki_variants": "noştu",
      "lerch_variants": "nó̤štu; no̤štu; no̤štu,; nó̤štu.; nó̤štu:",
      "context_gloss_hints": "wrote",
      "related_glossary_hits": "",
      "example_ref": "uc-kardes-masali:tb03_l05:10",
      "example_token_zazaki": "noştu",
      "example_token_lerch": "nó̤štu",
      "example_line_zazaki": "dı saati şê, kağit akerd, wengd, awnya kê, dyewi kağiti noştu ekê",
      "example_line_lerch": "di̥ sá’ati šẹ̄, kaγít āké̱rd, we̱ṅd, auńā́ ke, d́é̱wi kaγíti nó̤štu é̱ke",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "qaifeti",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "qaifeti",
      "suggested_gloss_en": "coffeehouse keeper; RECIP",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "uc-kardes-masali:5",
      "lemma_hints": "qaifeti",
      "zazaki_variants": "qayfeçi; qayfêçira; Qayfeçi; qayfetira; Qayfeti",
      "lerch_variants": "qaife̱t̮í; qaifet̮íra:; Qaife̱t̮í; qaife̱tíra; Qaife̱tí",
      "context_gloss_hints": "coffeehouse keeper; RECIP",
      "related_glossary_hits": "",
      "example_ref": "uc-kardes-masali:tb07_l11:2",
      "example_token_zazaki": "qayfeçi",
      "example_token_lerch": "qaife̱t̮í",
      "example_line_zazaki": "berd yaw qayfeçi 'hêtê ver da. 'Hasanêki va kê qayfêçira: ağa,",
      "example_line_lerch": "be̱rd yau qaife̱t̮í h̔ēte ve̱r dā. H̔asanéki vā ke qaifet̮íra: aγá,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "sahrestan",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "sahrestan",
      "suggested_gloss_en": "town",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "kauge-nyerib-u-hyeni:5",
      "lemma_hints": "sahrestan",
      "zazaki_variants": "şahrêstan; şahrêstang",
      "lerch_variants": "šahrestān; šáhrestān; šahrestāṅ,; šahrestā́n",
      "context_gloss_hints": "town",
      "related_glossary_hits": "Sahrestdn [lerch_glossary_p210_r0349:entry]: Stadt; vgl. npers",
      "example_ref": "kauge-nyerib-u-hyeni:h03_l10:9",
      "example_token_zazaki": "şahrêstan",
      "example_token_lerch": "šáhrestān",
      "example_line_zazaki": "Daqma begi zerêy 'Hyênidê dêlali vêyng da: nyêçaw ğarib şahrêstan",
      "example_line_lerch": "Dáqma bé̱gi ze̱reí Hʿyẹ̄́nide delā́li veiṅ dā: ńét̮au γarib šáhrestān",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "taalan",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "taalan",
      "suggested_gloss_en": "plunder",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 5,
      "text_count": 1,
      "text_counts": "kauge-nyerib-u-sivani:5",
      "lemma_hints": "taalan",
      "zazaki_variants": "taalan",
      "lerch_variants": "tá’alan",
      "context_gloss_hints": "plunder",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-sivani:s03_l11:12",
      "example_token_zazaki": "taalan",
      "example_token_lerch": "tá’alan",
      "example_line_zazaki": "va kê: twe ehêndê eskêri mê kişt, twê şeş dawê mê veşnay, taalan",
      "example_line_lerch": "vā ke: túe̱ é̱hende e̱skéri me kišt, túe še̱š dau’e me ve̱šnai, tá’alan",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "sebah",
      "suggested_action": "review_high_value",
      "suggested_headword": "sebah",
      "suggested_gloss_en": "morning",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 4,
      "text_count": 4,
      "text_counts": "degirmenci-ve-tilki:1; goin-puhu-kusunun-hikayesi:1; kauge-nyerib-u-hyeni:1; kauge-nyerib-u-sivani:1",
      "lemma_hints": "sebah",
      "zazaki_variants": "sêbah; Sêbah",
      "lerch_variants": "sebáh; Sebáh; sebāh; Sebáh",
      "context_gloss_hints": "morning",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf01_l03:0",
      "example_token_zazaki": "sêbah",
      "example_token_lerch": "sebáh",
      "example_line_zazaki": "sêbah werişt, ame arêyê, awnyaykê ardi mêsahıdi çınyi; aya şawê",
      "example_line_lerch": "sebáh we̱ríšt, āmé̱ āréye, auńaíke ā́rdi mesáhi̥di t̮í̥ńi; áya šaú’e",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "su",
      "suggested_action": "review_high_value",
      "suggested_headword": "su",
      "suggested_gloss_en": "went; shepherds-",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 4,
      "text_count": 4,
      "text_counts": "degirmenci-ve-tilki:1; goin-puhu-kusunun-hikayesi:1; kauge-nyerib-u-sivani:1; uc-kardes-masali:1",
      "lemma_hints": "su",
      "zazaki_variants": "şu; su; şü",
      "lerch_variants": "šu; šu; su-; šṳ́-",
      "context_gloss_hints": "went; shepherds-",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf05_l08:5",
      "example_token_zazaki": "şu",
      "example_token_lerch": "šu",
      "example_line_zazaki": "rira va kê: çêmçaqu paşa şu dêsmaç, nyêzana se byu, gnaw eru,",
      "example_line_lerch": "rira vā ke: t̮emt̮aqú pašá šu desmāt̮, ńézāna se̱ byu, gnau é̱ru,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "vinde",
      "suggested_action": "review_high_value",
      "suggested_headword": "vinde",
      "suggested_gloss_en": "stay",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 4,
      "text_count": 4,
      "text_counts": "degirmenci-ve-tilki:1; goin-puhu-kusunun-hikayesi:1; kauge-nyerib-u-sivani:1; uc-kardes-masali:1",
      "lemma_hints": "vinde",
      "zazaki_variants": "vındê; vindê",
      "lerch_variants": "vínde,; ví̥nde.; ví̥nde,; vi̥ndé,",
      "context_gloss_hints": "stay",
      "related_glossary_hits": "venert [lerch_glossary_p219_r0571:entry]: stood / sat / remained | vindßn’a [lerch_glossary_p219_r0580:entry]: (ich) bleibe, s. venden’a. vjndd, bleibe stehen, 57.6. äqjli vinde, bleibe vern...",
      "example_ref": "degirmenci-ve-tilki:mf04_l14:4",
      "example_token_zazaki": "vindê",
      "example_token_lerch": "vínde,",
      "example_line_zazaki": "metêrsê, ez nyêvêrdana, aqıli vindê, paşay Mısri nêkay ame zerê,",
      "example_line_lerch": "mé̱terse, e̱z ńeverdā́na, āqí̥li vínde, pašai Mí̥sri nekaí āmé̱ zé̱re,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "geraute",
      "suggested_action": "review_high_value",
      "suggested_headword": "geraute",
      "suggested_gloss_en": "took",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 4,
      "text_count": 3,
      "text_counts": "uc-kardes-masali:2; ali-agha-ladi-kelhani:1; degirmenci-ve-tilki:1",
      "lemma_hints": "geraute",
      "zazaki_variants": "gêrawtê",
      "lerch_variants": "geraúte; geraúte; geraúte,",
      "context_gloss_hints": "took",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a04_l01:9",
      "example_token_zazaki": "gêrawtê",
      "example_token_lerch": "geraúte",
      "example_line_zazaki": "xoê berd zerêy şibakê, yaw xancêri zerêy şıbakêdê di gêrawtê vera,",
      "example_line_lerch": "χóe be̱rd ze̱reí šibāke, yau χand̮éri ze̱reí ši̥bā́kede dī geraúte vé̱ra,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "lingeru",
      "suggested_action": "review_high_value",
      "suggested_headword": "lingeru",
      "suggested_gloss_en": "feet",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 4,
      "text_count": 3,
      "text_counts": "kauge-nyerib-u-sivani:2; degirmenci-ve-tilki:1; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "lingeru",
      "zazaki_variants": "lingêru",
      "lerch_variants": "língeru.; língeru,; líṅgeru; líṅgeru,",
      "context_gloss_hints": "feet",
      "related_glossary_hits": "ling [lerch_glossary_p213_r0417:entry]: Bein. Vgl. Krm. ling.",
      "example_ref": "degirmenci-ve-tilki:mf05_l01:2",
      "example_token_zazaki": "lingêru",
      "example_token_lerch": "língeru.",
      "example_line_zazaki": "warzê, law lingêru. Çêmçaqu paşa va kê lwêra: nêkay paşay Mışri",
      "example_line_lerch": "wárze, lau língeru. T̮emt̮aqú pašá vā ke lúera: nekaí pašai Mí̥šri",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "teber",
      "suggested_action": "review_high_value",
      "suggested_headword": "teber",
      "suggested_gloss_en": "outside",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 4,
      "text_count": 3,
      "text_counts": "ali-agha-ladi-kelhani:2; degirmenci-ve-tilki:1; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "teber",
      "zazaki_variants": "tebêr",
      "lerch_variants": "te̱bér,; te̱bér,",
      "context_gloss_hints": "outside",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a03_l06:8",
      "example_token_zazaki": "tebêr",
      "example_token_lerch": "te̱bér,",
      "example_line_zazaki": "kişêni. 'Hali xancêray A'hmêdi nyêday cê. 'Hal şê tebêr, eskêri",
      "example_line_lerch": "kišén’i. Hʿāli χand̮érai Ah̔médi ńédai d̮e. Hʿāl šẹ̄ te̱bér, e̱skéri",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "tewi",
      "suggested_action": "review_high_value",
      "suggested_headword": "tewi",
      "suggested_gloss_en": "no one",
      "suggested_gloss_tr": "",
      "rationale": "Occurs in multiple texts and should be checked against the scanned glossary/headword policy.",
      "token_count": 4,
      "text_count": 3,
      "text_counts": "kauge-nyerib-u-hyeni:2; ali-agha-ladi-kelhani:1; kauge-nyerib-u-sivani:1",
      "lemma_hints": "tewi",
      "zazaki_variants": "çewi",
      "lerch_variants": "t̮é̱wi; t̮é̱wi; t̮é̱wi",
      "context_gloss_hints": "no one",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a01_l03:6",
      "example_token_zazaki": "çewi",
      "example_token_lerch": "t̮é̱wi",
      "example_line_zazaki": "kişti. Çawdi Ali ağay çi nyêbê, çewi desti Ali ağay nyêgêrawt. Ali",
      "example_line_lerch": "kíšti. T̮aúdi Áli aγaí t̮i ńébe, t̮é̱wi dé̱sti Áli aγaí ńegeraút. Áli",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "akerd",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "akerd",
      "suggested_gloss_en": "opened",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:3; kauge-nyerib-u-sivani:1",
      "lemma_hints": "akerd",
      "zazaki_variants": "akêrd; akerd",
      "lerch_variants": "ākérd,; āké̱rd,; aké̱rd,; akērd,",
      "context_gloss_hints": "opened",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-sivani:s01_l03:3",
      "example_token_zazaki": "akêrd",
      "example_token_lerch": "ākérd,",
      "example_line_zazaki": "Mêla A'hmêdi Qafan akêrd, purti Mêla A'hmêdi Qafan gêrawt",
      "example_line_lerch": "Mél’a Ah̔médi Qafán ākérd, púrti Mél’a Ah̔médi Qafán geraút",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "dumilbazi",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "dumilbazi",
      "suggested_gloss_en": "drum",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-sivani:3; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "dumilbazi",
      "zazaki_variants": "dümilbazi; dumilbazi; Dumilbazi",
      "lerch_variants": "dṳ́milbā́zi; dúmilbā́zi; Dúmilbāzi",
      "context_gloss_hints": "drum",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h04_l11:5",
      "example_token_zazaki": "dumilbazi",
      "example_token_lerch": "dúmilbā́zi",
      "example_line_zazaki": "Xalef ağa werişt bê êspar, dumilbazi da püroê, kawt eskêri",
      "example_line_lerch": "Χalé̱f aγá we̱ríšt be espā́r, dúmilbā́zi dā pṳ́roe, kaut e̱skéri",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "eru",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "eru",
      "suggested_gloss_en": "earth",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "degirmenci-ve-tilki:2; uc-kardes-masali:2",
      "lemma_hints": "eru",
      "zazaki_variants": "eru",
      "lerch_variants": "é̱ru,; é̱ru.",
      "context_gloss_hints": "earth",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf05_l07:6",
      "example_token_zazaki": "eru",
      "example_token_lerch": "é̱ru,",
      "example_line_zazaki": "lwê şi gêray, arêwangçi di, gnaw eru, merdu. Lwê amêy, paşay Mıs-",
      "example_line_lerch": "lúe ši geraí, ārewāṅt̮í dī, gnau é̱ru, mé̱rdu. Lúe āmeí, pašai Mí̥s-",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "garib",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "γarib",
      "suggested_gloss_en": "stranger; PL; EZ/OBL",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "ali-agha-ladi-kelhani:3; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "γarib; garib",
      "zazaki_variants": "ğaribana; ğarib",
      "lerch_variants": "γaribā́na; γarib",
      "context_gloss_hints": "stranger; PL; EZ/OBL; outsider",
      "related_glossary_hits": "",
      "example_ref": "ali-agha-ladi-kelhani:a04_l08:2",
      "example_token_zazaki": "ğaribana",
      "example_token_lerch": "γaribā́na",
      "example_line_zazaki": "hêyşt merdümi ğaribana pyêru mêndi wadedê. Soba Mêlay Rêsa",
      "example_line_lerch": "heišt me̱rdṳ́mi γaribā́na pyéru méndi wáde̱de. So̤bá Mél’ai Resá",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "hemam",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "hemam",
      "suggested_gloss_en": "bath; ABL",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "degirmenci-ve-tilki:2; uc-kardes-masali:2",
      "lemma_hints": "hemam",
      "zazaki_variants": "'hemam; 'hêmam; 'hêmamra",
      "lerch_variants": "h̔é̱m’ām,; h̔e̱m’ām,; h̔emám,; h̔emā́mra",
      "context_gloss_hints": "bath; ABL",
      "related_glossary_hits": "hema [lerch_glossary_p201_r0107:entry]: however; only",
      "example_ref": "degirmenci-ve-tilki:mf03_l12:5",
      "example_token_zazaki": "'hemam",
      "example_token_lerch": "h̔é̱m’ām,",
      "example_line_zazaki": "şadê Mısri wayştê, warzê, şwê 'hemam, xoê bışu, temiz kê, byê,",
      "example_line_lerch": "šáde Mi̥sri waíšte, wárze, šúe h̔é̱m’ām, χóe bi̥šú, te̱míz ke, bye,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "qamek",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "qamek",
      "suggested_gloss_en": "some; whoever",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "degirmenci-ve-tilki:3; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "qamek",
      "zazaki_variants": "qamêk",
      "lerch_variants": "qā́mek; qāmek; qā́meḱ",
      "context_gloss_hints": "some; whoever",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf04_l05:3",
      "example_token_zazaki": "qamêk",
      "example_token_lerch": "qā́mek",
      "example_line_zazaki": "sêlam bêdu. Eskêri qamêk va: enoê delu, enoê dêlu; qamêk va:",
      "example_line_lerch": "selám bedú. E̱skéri qā́mek vā: ḗ̱n’oe dé̱lu, ḗ̱n’oe délu; qā́mek vā:",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "qauwi",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "qauwi",
      "suggested_gloss_en": "surely; why",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "goin-puhu-kusunun-hikayesi:2; uc-kardes-masali:2",
      "lemma_hints": "qauwi",
      "zazaki_variants": "qawi",
      "lerch_variants": "qaúwi; qaúwi",
      "context_gloss_hints": "surely; why",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g03_l06:4",
      "example_token_zazaki": "qawi",
      "example_token_lerch": "qaúwi",
      "example_line_zazaki": "xoêra va kê: twê qawi laci mê kiştu, way cêy bi şewi 'hawni xoê-",
      "example_line_lerch": "χóera vā ke: túe qaúwi lā́d̮i me kíštu, wai d̮ei bi še̱wi h̔aúni χóe-",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "teni",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "teni",
      "suggested_gloss_en": "persons",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "ali-agha-ladi-kelhani:3; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "teni",
      "zazaki_variants": "teni; têni",
      "lerch_variants": "té̱ni; tén’i",
      "context_gloss_hints": "persons",
      "related_glossary_hits": "tenitaqü [lerch_glossary_p205_r0213:entry]: temteqü pa§ä, 84 sq.",
      "example_ref": "ali-agha-ladi-kelhani:a04_l04:9",
      "example_token_zazaki": "teni",
      "example_token_lerch": "té̱ni",
      "example_line_zazaki": "çimyiru, goêni byê A'hmêdi çimi. A'hmêd hyêrs bê, 'hawt teni pêy",
      "example_line_lerch": "t̮ímyiru, gó’eni bíe Ah̔médi t̮ími. Ah̔méd hyẹ̄rs be, h̔aut té̱ni pei",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "vesnai",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "vesnai",
      "suggested_gloss_en": "burned",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-sivani:3; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "vesnai",
      "zazaki_variants": "veşnay",
      "lerch_variants": "ve̱šnaí,; vé̱šnai,; ve̱šnai,",
      "context_gloss_hints": "burned",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h05_l13:1",
      "example_token_zazaki": "veşnay",
      "example_token_lerch": "ve̱šnaí,",
      "example_line_zazaki": "'Hyêni veşnay, serêy Xalil êfêndi têra kêrd, ard, da Xalef",
      "example_line_lerch": "Hʿyẹ̄́ni ve̱šnaí, sé̱rei Χalíl eféndi terá kerd, ārd, dā Χalé̱f",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "vesnena",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "vesnena",
      "suggested_gloss_en": "I will burn",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-hyeni:3; kauge-nyerib-u-sivani:1",
      "lemma_hints": "vesnena",
      "zazaki_variants": "veşnêna; vêşnêna",
      "lerch_variants": "ve̱šnén’a,; vešnén’a.; ve̱šnén’a.",
      "context_gloss_hints": "I will burn",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h04_l04:2",
      "example_token_zazaki": "vêşnêna",
      "example_token_lerch": "vešnén’a.",
      "example_line_zazaki": "emşoê şahrêstan vêşnêna.",
      "example_line_lerch": "é̱mšoe šahrestān vešnén’a.",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "warzi",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "warzi",
      "suggested_gloss_en": "get up; rise",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:3; kauge-nyerib-u-hyeni:1",
      "lemma_hints": "warzi",
      "zazaki_variants": "warzi",
      "lerch_variants": "wárzi,; wārzi,; wárzi",
      "context_gloss_hints": "get up; rise",
      "related_glossary_hits": "warzdn’a [lerch_glossary_p220_r0589:entry]: (ich) erhebe mich, stehe auf. wärzi, stehet auf. weriät, erhob sich, stand auf....",
      "example_ref": "kauge-nyerib-u-hyeni:h05_l07:2",
      "example_token_zazaki": "warzi",
      "example_token_lerch": "wárzi,",
      "example_line_zazaki": "ağay amê, warzi, şyêri metırisi. Xalef ağay eskêri xoêra va kê:",
      "example_line_lerch": "āγái āmé, wárzi, šyẹ̄́ri me̱ti̥rísi. Χalé̱f aγái e̱skéri χóera vā ke:",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "wesi",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "wesi",
      "suggested_gloss_en": "reconciliation",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "kauge-nyerib-u-hyeni:2; kauge-nyerib-u-sivani:2",
      "lemma_hints": "wesi",
      "zazaki_variants": "weşi; weşı",
      "lerch_variants": "wé̱ši̥; wé̱ši,; wé̱ši; wé̱ši,",
      "context_gloss_hints": "reconciliation",
      "related_glossary_hits": "",
      "example_ref": "kauge-nyerib-u-hyeni:h09_l06:7",
      "example_token_zazaki": "weşı",
      "example_token_lerch": "wé̱ši̥",
      "example_line_zazaki": "Xalef ağay daw pyêru byêri, ma pya weşı ki. Ağay Zıriki werişti,",
      "example_line_lerch": "Χalé̱f aγái dau pyéru byẹ̄́ri, mā pyā wé̱ši̥ ki. Aγái Zí̥riki we̱ríšti,",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "yauna",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "yauna",
      "suggested_gloss_en": "another",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 2,
      "text_counts": "uc-kardes-masali:3; goin-puhu-kusunun-hikayesi:1",
      "lemma_hints": "yauna",
      "zazaki_variants": "yawna",
      "lerch_variants": "yaúna; yaúna; yaū́na",
      "context_gloss_hints": "another",
      "related_glossary_hits": "",
      "example_ref": "goin-puhu-kusunun-hikayesi:g01_l02:7",
      "example_token_zazaki": "yawna",
      "example_token_lerch": "yaúna",
      "example_line_zazaki": "têra bi. Cênyay merd, pêynıdê myêrdê şê yawna cêni ardê. Dı",
      "example_line_lerch": "terá bī. D̮éniai me̱rd, peíni̥de myérde šẹ̄ yaúna d̮éni ā́rde. Di̥",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "auke",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "auke",
      "suggested_gloss_en": "water; from",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 1,
      "text_counts": "degirmenci-ve-tilki:4",
      "lemma_hints": "auke",
      "zazaki_variants": "awkê; awkêra",
      "lerch_variants": "aúke; aúkera",
      "context_gloss_hints": "water; from",
      "related_glossary_hits": "",
      "example_ref": "degirmenci-ve-tilki:mf03_l03:5",
      "example_token_zazaki": "awkêra",
      "example_token_lerch": "aúkera",
      "example_line_zazaki": "lingê, mê enoê dest tepişt awkêra vecyaya tebêr, çêmçêqu paşa",
      "example_line_lerch": "líṅge, me ḗ̱n’oe de̱st te̱píšt aúkera ve̱d̮iáya te̱bér, t̮emt̮equ pašá",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "basi",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "basi",
      "suggested_gloss_en": "captain; RECIP",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 1,
      "text_counts": "uc-kardes-masali:4",
      "lemma_hints": "basi",
      "zazaki_variants": "başira; başi",
      "lerch_variants": "baší; bašíra; bašīra:",
      "context_gloss_hints": "captain; RECIP",
      "related_glossary_hits": "",
      "example_ref": "uc-kardes-masali:tb08_l09:7",
      "example_token_zazaki": "başira",
      "example_token_lerch": "bašíra",
      "example_line_zazaki": "ban 'hêmamra vet gêrawt berd têslimê qabas başira va kê: enoê",
      "example_line_lerch": "bán h̔emā́mra ve̱t geraút be̱rd teslī́me qabā́s bašíra vā ke: ḗ̱n’oe",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    },
    {
      "lemma_key": "bia",
      "suggested_action": "review_lower_priority",
      "suggested_headword": "bia",
      "suggested_gloss_en": "was",
      "suggested_gloss_tr": "",
      "rationale": "Included because it occurs frequently or has a useful context gloss, but needs manual headword judgment.",
      "token_count": 4,
      "text_count": 1,
      "text_counts": "gespraech-mit-hassan:4",
      "lemma_hints": "bia",
      "zazaki_variants": "bya",
      "lerch_variants": "bía;; bía,; bía.",
      "context_gloss_hints": "was",
      "related_glossary_hits": "",
      "example_ref": "gespraech-mit-hassan:h03_l11:2",
      "example_token_zazaki": "bya",
      "example_token_lerch": "bía;",
      "example_line_zazaki": "ez tedê bya; kawğei Sivani û Avdula begi mê di, ez tedê bya;",
      "example_line_lerch": "e̱z té̱de bía; kauγé̱’i Sivā́ni u Avdúla bé̱gi me dī, e̱z té̱de bía;",
      "review_status": "needs_human_review",
      "reviewer_note": ""
    }
  ]
};
